GET http://localhost:4004/CatalogService/MemberMaster

###
POST http://localhost:4004/CatalogService/MemberMaster
Content-Type: application/json

{
      "memberName": "Sourit Chakraborty",
      "phoneNo" : "+91 8777696112",
      "email": "abcd@abc.com",
      "dob": "1995-11-13",
      "gender": ""
}

### Boost Testing
POST http://localhost:4004/CatalogService/MemberMaster('02BD2137-0890-1EEA-A6C2-BB55C19787FB')/CatalogService.boost
Content-Type: application/json

{

}
